export type ListingConfig = {
  apiBase: string; // base endpoint e.g. /api/tuition-private-classes
  titleField?: string;
  subtitleField?: string;
  defaultFields?: string[];
  featureKeys?: string[];
};

// Centralized config for known listing types
 export const listingConfigs: Record<string, ListingConfig> = {
  "tuition-private-classes": {
    apiBase: "/api/admin/tuition-private-classes",
    titleField: "title",
    subtitleField: "tutorName",
    defaultFields: [
      "listingType",
      "subjectCategory",
      "teachingMode",
      "classType",
      "tutorQualification",
      "tutorExperienceYears",
      "gradeLevel",
      "minGrade",
      "maxGrade",
      "board",
      "batchSize",
      "feePerMonth",
      "feePerHour",
      "feePerSubject",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "isActive",
      "isFeatured",
      "viewCount",
     
    ],
    featureKeys: [
      "demoClassAvailable",
      "studyMaterialProvided",
      "testSeriesIncluded",
      "doubtClearingSessions",
      "flexibleTimings",
      "weekendClasses",
      "homeTuitionAvailable",
      "onlineClassesAvailable",
    ],
  },
  // Cars & Bikes
  "cars-bikes": {
    apiBase: "/api/admin/cars-bikes",
    titleField: "title",
    subtitleField: "model",
    defaultFields: ["listingType", "vehicleType", "brand", "model", "year", "price", "emiAvailable", "emiStartingFrom", "emiMonths", "kilometersDriven", "fuelType", "transmission", "color", "ownerNumber", "registrationNumber", "insuranceValidUntil", "condition", "isNegotiable", "city", "fullAddress", "contactPerson", "contactPhone", "isActive", "isFeatured", "viewCount"],
  },
  // Second Hand Cars & Bikes
  "second-hand-cars-bikes": {
    apiBase: "/api/admin/second-hand-cars-bikes",
    titleField: "title",
    subtitleField: "model",
    defaultFields: [
      "listingType",
      "vehicleType",
      "brand",
      "model",
      "variant",
      "year",
      "price",
      "emiAvailable",
      "emiStartingFrom",
      "emiMonths",
      "kilometersDriven",
      "fuelType",
      "transmission",
      "ownerNumber",
      "registrationNumber",
      "registrationState",
      "registrationYear",
      "insuranceType",
      "insuranceValidUntil",
      "taxValidity",
      "color",
      "bodyType",
      "seatingCapacity",
      "engineCapacity",
      "mileageKmpl",
      "condition",
      "accidentHistory",
      "floodAffected",
      "serviceRecordsAvailable",
      "nocAvailable",
      "isNegotiable",
      "exchangeAccepted",
      "testDriveAvailable",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "isActive",
      "isFeatured",
      "isVerified",
      "viewCount",
     
    ],
  },
  // Fashion & Beauty Products
  "fashion-beauty-products": {
    apiBase: "/api/admin/fashion-beauty-products",
    titleField: "title",
    subtitleField: "productName",
    defaultFields: [
      "listingType",
      "category",
      "subcategory",
      "productType",
      "brand",
      "productName",
      "color",
      "size",
      "material",
      "pattern",
      "style",
      "occasion",
      "gender",
      "ageGroup",
      "fitType",
      "sleeveType",
      "neckType",
      "length",
      "waistSize",
      "inseam",
      "productVolume",
      "skinType",
      "hairType",
      "fragranceType",
      "ingredients",
      "expiryDate",
      "manufacturingDate",
      "shelfLife",
      "price",
      "mrp",
      "discountPercentage",
      "rentalPricePerDay",
      "rentalPricePerWeek",
      "rentalPricePerMonth",
      "minimumRentalPeriod",
      "rentalPeriodUnit",
      "securityDeposit",
      "condition",
      "usageDuration",
      "purchaseDate",
      "ageInMonths",
      "qualityGrade",
      "isOriginal",
      "brandAuthorized",
      "certificateAvailable",
      "authenticationProof",
      "careInstructions",
      "washingInstructions",
      "dryCleanOnly",
      "ironSafe",
      "fabricCare",
      "dermatologicallyTested",
      "crueltyFree",
      "vegan",
      "organic",
      "parabenFree",
      "sulfateFree",
      "allergenInfo",
      "inStock",
      "stockQuantity",
      "sizesAvailable",
      "colorsAvailable",
      "variantOptions",
      "customizationAvailable",
      "customSizing",
      "personalizationOptions",
      "tailoringIncluded",
      "videos",
      "sizeChart",
      "productBrochure",
      "keyFeatures",
      "fabricFeatures",
      "specialFeatures",
      "includedItems",
      "boxContents",
      "isOnSale",
      "saleEndDate",
      "bankOffers",
      "comboOffers",
      "bulkDiscountAvailable",
      "returnPolicy",
      "returnPeriodDays",
      "replacementPolicy",
      "exchangeAvailable",
      "refundAvailable",
      "warrantyAvailable",
      "warrantyPeriod",
      "sellerType",
      "shopName",
      "boutiqueName",
      "designerName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "alternatePhone",
      "whatsappAvailable",
      "whatsappNumber",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "deliveryAvailable",
      "deliveryCharges",
      "freeDelivery",
      "freeDeliveryAbove",
      "sameDayDelivery",
      "expressDelivery",
      "deliveryAreas",
      "shippingOptions",
      "codAvailable",
      "isActive",
      "isFeatured",
      "isVerified",
      "availabilityStatus",
      "viewCount",
     
    ],
  },
  // Car & Bike Rentals
  "car-bike-rentals": {
    apiBase: "/api/admin/car-bike-rentals",
    titleField: "title",
    subtitleField: "brand",
    defaultFields: ["rentalType", "brand", "model", "rentalPricePerDay", "rentalPricePerHour", "minimumRentalDuration", "licenseRequired", "driverAvailable", "city", "fullAddress", "isActive", "isFeatured", "viewCount"],
  },
  // Agents & Agencies
  "agents-agencies": {
    apiBase: "/api/admin/agents-agencies",
    titleField: "title",
    subtitleField: "agencyName",
    defaultFields: [
      "agencyType",
      "ownerName",
      "establishedYear",
      "licenseNumber",
      "specialization",
      "services",
      "serviceAreas",
      "teamSize",
      "propertiesHandled",
      "verified",
      "licensed",
      "freeConsultation",
      "homeVisit",
      "onlineService",
      "emergencyService",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "socialMediaLinks",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "verified",
      "licensed",
      "freeConsultation",
      "homeVisit",
      "onlineService",
      "emergencyService",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Professional Services
  "professional-services": {
    apiBase: "/api/admin/professional-services",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "professionalName",
      "qualification",
      "experienceYears",
      "certifications",
      "specialization",
      "serviceAreas",
      "hourlyRate",
      "consultationFee",
      "freeConsultation",
      "homeService",
      "onlineService",
      "emergencyService",
      "licensedProfessional",
      "insured",
      "verified",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "website",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "verified",
      "licensedProfessional",
      "insured",
      "freeConsultation",
      "homeService",
      "onlineService",
      "emergencyService",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Labor & Worker Services
  "labor-worker-services": {
    apiBase: "/api/admin/labor-worker-services",
    titleField: "title",
    subtitleField: "workerName",
    defaultFields: [
      "workerType",
      "businessName",
      "workerName",
      "skills",
      "experience",
      "age",
      "gender",
      "availability",
      "hourlyRate",
      "dailyRate",
      "monthlyRate",
      "freeDemo",
      "pickupAvailable",
      "onsiteAvailable",
      "certified",
      "backgroundVerified",
      "toolsProvided",
      "transportAvailable",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languageKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeDemo",
      "pickupAvailable",
      "onsiteAvailable",
      "certified",
      "backgroundVerified",
      "toolsProvided",
      "transportAvailable",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Engineering & IT Services
  "engineering-it-services": {
    apiBase: "/api/admin/engineering-it-services",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "businessName",
      "teamSize",
      "foundedYear",
      "specialization",
      "technologies",
      "certifications",
      "serviceAreas",
      "hourlyRate",
      "projectBasedPricing",
      "freeConsultation",
      "remoteService",
      "onsiteService",
      "emergencySupport",
      "isoCertified",
      "msmeRegistered",
      "governmentContractor",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeConsultation",
      "remoteService",
      "onsiteService",
      "emergencySupport",
      "isoCertified",
      "msmeRegistered",
      "governmentContractor",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Legal & Banking Services
  "legal-banking-services": {
    apiBase: "/api/admin/legal-banking-services",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "businessName",
      "firmName",
      "establishedYear",
      "specialization",
      "licenseNumber",
      "barCouncilNumber",
      "serviceAreas",
      "consultationFee",
      "freeConsultation",
      "onlineConsultation",
      "homeVisit",
      "courtRepresentation",
      "documentDrafting",
      "notarized",
      "registered",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeConsultation",
      "onlineConsultation",
      "homeVisit",
      "courtRepresentation",
      "documentDrafting",
      "notarized",
      "registered",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Insurance Services
  "insurance-services": {
    apiBase: "/api/admin/insurance-services",
    titleField: "title",
    subtitleField: "companyName",
    defaultFields: [
      "insuranceType",
      "companyName",
      "agentName",
      "licenseNumber",
      "experience",
      "specialization",
      "covers",
      "freeQuote",
      "onlinePurchase",
      "homeVisit",
      "claimAssistance",
      "cashlessClaim",
      "roadSideAssistance",
      "support24x7",
      "tieUpHospitals",
      "networkGarages",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeQuote",
      "onlinePurchase",
      "homeVisit",
      "claimAssistance",
      "cashlessClaim",
      "roadSideAssistance",
      "support24x7",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // NGO & Social Services
  "ngo-social-services": {
    apiBase: "/api/admin/ngo-social-services",
    titleField: "title",
    subtitleField: "organizationName",
    defaultFields: [
      "ngoType",
      "organizationName",
      "registrationNumber",
      "foundedYear",
      "mission",
      "vision",
      "focusAreas",
      "targetBeneficiaries",
      "servicesOffered",
      "volunteerOpportunities",
      "donationAccepted",
      "ngoAccredited",
      "governmentRecognized",
      "onlineServices",
      "freeServices",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "volunteerOpportunities",
      "donationAccepted",
      "ngoAccredited",
      "governmentRecognized",
      "onlineServices",
      "freeServices",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Add other mapping entries as needed. Fallback: infer from type param
};

export const getConfigForType = (type: string) => {
  return listingConfigs[type];
};
