export type ListingConfig = {
  apiBase: string; // base endpoint e.g. /api/tuition-private-classes
  titleField?: string;
  subtitleField?: string;
  defaultFields?: string[];
  featureKeys?: string[];
};

// Centralized config for known listing types
 export const listingConfigs: Record<string, ListingConfig> = {
  "tuition-private-classes": {
    apiBase: "/api/admin/tuition-private-classes",
    titleField: "title",
    subtitleField: "tutorName",
    defaultFields: [
      "listingType",
      "subjectCategory",
      "teachingMode",
      "classType",
      "tutorQualification",
      "tutorExperienceYears",
      "gradeLevel",
      "minGrade",
      "maxGrade",
      "board",
      "batchSize",
      "feePerMonth",
      "feePerHour",
      "feePerSubject",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "isActive",
      "isFeatured",
      "viewCount",
     
    ],
    featureKeys: [
      "demoClassAvailable",
      "studyMaterialProvided",
      "testSeriesIncluded",
      "doubtClearingSessions",
      "flexibleTimings",
      "weekendClasses",
      "homeTuitionAvailable",
      "onlineClassesAvailable",
    ],
  },
  // Cars & Bikes
  "cars-bikes": {
    apiBase: "/api/admin/cars-bikes",
    titleField: "title",
    subtitleField: "model",
    defaultFields: ["listingType", "vehicleType", "brand", "model", "year", "price", "emiAvailable", "emiStartingFrom", "emiMonths", "kilometersDriven", "fuelType", "transmission", "color", "ownerNumber", "registrationNumber", "insuranceValidUntil", "condition", "isNegotiable", "city", "fullAddress", "contactPerson", "contactPhone", "isActive", "isFeatured", "viewCount"],
  },
  // Second Hand Cars & Bikes
  "second-hand-cars-bikes": {
    apiBase: "/api/admin/second-hand-cars-bikes",
    titleField: "title",
    subtitleField: "model",
    defaultFields: [
      "listingType",
      "vehicleType",
      "brand",
      "model",
      "variant",
      "year",
      "price",
      "emiAvailable",
      "emiStartingFrom",
      "emiMonths",
      "kilometersDriven",
      "fuelType",
      "transmission",
      "ownerNumber",
      "registrationNumber",
      "registrationState",
      "registrationYear",
      "insuranceType",
      "insuranceValidUntil",
      "taxValidity",
      "color",
      "bodyType",
      "seatingCapacity",
      "engineCapacity",
      "mileageKmpl",
      "condition",
      "accidentHistory",
      "floodAffected",
      "serviceRecordsAvailable",
      "nocAvailable",
      "isNegotiable",
      "exchangeAccepted",
      "testDriveAvailable",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "isActive",
      "isFeatured",
      "isVerified",
      "viewCount",
     
    ],
  },
  // Fashion & Beauty Products
  "fashion-beauty-products": {
    apiBase: "/api/admin/fashion-beauty-products",
    titleField: "title",
    subtitleField: "productName",
    defaultFields: [
      "listingType",
      "category",
      "subcategory",
      "productType",
      "brand",
      "productName",
      "color",
      "size",
      "material",
      "pattern",
      "style",
      "occasion",
      "gender",
      "ageGroup",
      "fitType",
      "sleeveType",
      "neckType",
      "length",
      "waistSize",
      "inseam",
      "productVolume",
      "skinType",
      "hairType",
      "fragranceType",
      "ingredients",
      "expiryDate",
      "manufacturingDate",
      "shelfLife",
      "price",
      "mrp",
      "discountPercentage",
      "rentalPricePerDay",
      "rentalPricePerWeek",
      "rentalPricePerMonth",
      "minimumRentalPeriod",
      "rentalPeriodUnit",
      "securityDeposit",
      "condition",
      "usageDuration",
      "purchaseDate",
      "ageInMonths",
      "qualityGrade",
      "isOriginal",
      "brandAuthorized",
      "certificateAvailable",
      "authenticationProof",
      "careInstructions",
      "washingInstructions",
      "dryCleanOnly",
      "ironSafe",
      "fabricCare",
      "dermatologicallyTested",
      "crueltyFree",
      "vegan",
      "organic",
      "parabenFree",
      "sulfateFree",
      "allergenInfo",
      "inStock",
      "stockQuantity",
      "sizesAvailable",
      "colorsAvailable",
      "variantOptions",
      "customizationAvailable",
      "customSizing",
      "personalizationOptions",
      "tailoringIncluded",
      "videos",
      "sizeChart",
      "productBrochure",
      "keyFeatures",
      "fabricFeatures",
      "specialFeatures",
      "includedItems",
      "boxContents",
      "isOnSale",
      "saleEndDate",
      "bankOffers",
      "comboOffers",
      "bulkDiscountAvailable",
      "returnPolicy",
      "returnPeriodDays",
      "replacementPolicy",
      "exchangeAvailable",
      "refundAvailable",
      "warrantyAvailable",
      "warrantyPeriod",
      "sellerType",
      "shopName",
      "boutiqueName",
      "designerName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "alternatePhone",
      "whatsappAvailable",
      "whatsappNumber",
      "country",
      "stateProvince",
      "city",
      "areaName",
      "fullAddress",
      "deliveryAvailable",
      "deliveryCharges",
      "freeDelivery",
      "freeDeliveryAbove",
      "sameDayDelivery",
      "expressDelivery",
      "deliveryAreas",
      "shippingOptions",
      "codAvailable",
      "isActive",
      "isFeatured",
      "isVerified",
      "availabilityStatus",
      "viewCount",
     
    ],
  },
  // Car & Bike Rentals
  "car-bike-rentals": {
    apiBase: "/api/admin/car-bike-rentals",
    titleField: "title",
    subtitleField: "brand",
    defaultFields: ["rentalType", "brand", "model", "rentalPricePerDay", "rentalPricePerHour", "minimumRentalDuration", "licenseRequired", "driverAvailable", "city", "fullAddress", "isActive", "isFeatured", "viewCount"],
  },
  // Agents & Agencies
  "agents-agencies": {
    apiBase: "/api/admin/agents-agencies",
    titleField: "title",
    subtitleField: "agencyName",
    defaultFields: [
      "agencyType",
      "ownerName",
      "establishedYear",
      "licenseNumber",
      "specialization",
      "services",
      "serviceAreas",
      "teamSize",
      "propertiesHandled",
      "verified",
      "licensed",
      "freeConsultation",
      "homeVisit",
      "onlineService",
      "emergencyService",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "socialMediaLinks",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "verified",
      "licensed",
      "freeConsultation",
      "homeVisit",
      "onlineService",
      "emergencyService",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Professional Services
  "professional-services": {
    apiBase: "/api/admin/professional-services",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "professionalName",
      "qualification",
      "experienceYears",
      "certifications",
      "specialization",
      "serviceAreas",
      "hourlyRate",
      "consultationFee",
      "freeConsultation",
      "homeService",
      "onlineService",
      "emergencyService",
      "licensedProfessional",
      "insured",
      "verified",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "website",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "verified",
      "licensedProfessional",
      "insured",
      "freeConsultation",
      "homeService",
      "onlineService",
      "emergencyService",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Labor & Worker Services
  "labor-worker-services": {
    apiBase: "/api/admin/labor-worker-services",
    titleField: "title",
    subtitleField: "workerName",
    defaultFields: [
      "workerType",
      "businessName",
      "workerName",
      "skills",
      "experience",
      "age",
      "gender",
      "availability",
      "hourlyRate",
      "dailyRate",
      "monthlyRate",
      "freeDemo",
      "pickupAvailable",
      "onsiteAvailable",
      "certified",
      "backgroundVerified",
      "toolsProvided",
      "transportAvailable",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languageKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeDemo",
      "pickupAvailable",
      "onsiteAvailable",
      "certified",
      "backgroundVerified",
      "toolsProvided",
      "transportAvailable",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Engineering & IT Services
  "engineering-it-services": {
    apiBase: "/api/admin/engineering-it-services",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "businessName",
      "teamSize",
      "foundedYear",
      "specialization",
      "technologies",
      "certifications",
      "serviceAreas",
      "hourlyRate",
      "projectBasedPricing",
      "freeConsultation",
      "remoteService",
      "onsiteService",
      "emergencySupport",
      "isoCertified",
      "msmeRegistered",
      "governmentContractor",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeConsultation",
      "remoteService",
      "onsiteService",
      "emergencySupport",
      "isoCertified",
      "msmeRegistered",
      "governmentContractor",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Legal & Banking Services
  "legal-banking-services": {
    apiBase: "/api/admin/legal-banking-services",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "businessName",
      "firmName",
      "establishedYear",
      "specialization",
      "licenseNumber",
      "barCouncilNumber",
      "serviceAreas",
      "consultationFee",
      "freeConsultation",
      "onlineConsultation",
      "homeVisit",
      "courtRepresentation",
      "documentDrafting",
      "notarized",
      "registered",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeConsultation",
      "onlineConsultation",
      "homeVisit",
      "courtRepresentation",
      "documentDrafting",
      "notarized",
      "registered",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Insurance Services
  "insurance-services": {
    apiBase: "/api/admin/insurance-services",
    titleField: "title",
    subtitleField: "companyName",
    defaultFields: [
      "insuranceType",
      "companyName",
      "agentName",
      "licenseNumber",
      "experience",
      "specialization",
      "covers",
      "freeQuote",
      "onlinePurchase",
      "homeVisit",
      "claimAssistance",
      "cashlessClaim",
      "roadSideAssistance",
      "support24x7",
      "tieUpHospitals",
      "networkGarages",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeQuote",
      "onlinePurchase",
      "homeVisit",
      "claimAssistance",
      "cashlessClaim",
      "roadSideAssistance",
      "support24x7",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // NGO & Social Services
  "ngo-social-services": {
    apiBase: "/api/admin/ngo-social-services",
    titleField: "title",
    subtitleField: "organizationName",
    defaultFields: [
      "ngoType",
      "organizationName",
      "registrationNumber",
      "foundedYear",
      "mission",
      "vision",
      "focusAreas",
      "targetBeneficiaries",
      "servicesOffered",
      "volunteerOpportunities",
      "donationAccepted",
      "ngoAccredited",
      "governmentRecognized",
      "onlineServices",
      "freeServices",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "website",
      "whatsappAvailable",
      "city",
      "fullAddress",
      "workingHours",
      "available24_7",
      "languagesKnown",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "volunteerOpportunities",
      "donationAccepted",
      "ngoAccredited",
      "governmentRecognized",
      "onlineServices",
      "freeServices",
      "whatsappAvailable",
      "available24_7",
    ],
  },
  // Agriculture, Seeds & Farming
  "agriculture-seeds-farming": {
    apiBase: "/api/admin/agriculture",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "farmType",
      "businessName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "city",
      "state",
      "fullAddress",
      "farmSize",
      "organicFarming",
      "conventionalFarming",
      "hydroponics",
      "greenhouseFarming",
      "dairyFarming",
      "poultryFarming",
      "fishFarming",
      "seeds",
      "fertilizers",
      "pesticides",
      "agriculturalEquipment",
      "irrigationSystem",
      "organicCertified",
      "fssaiCertified",
      "qualityCheck",
      "deliveryAvailable",
      "wholesaleAvailable",
      "retailAvailable",
      "exportAvailable",
      "experienceYears",
      "certifications",
      "productPriceMin",
      "productPriceMax",
      "minimumOrderQuantity",
      "workingHours",
      "languagesKnown",
      "images",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "organicFarming",
      "conventionalFarming",
      "hydroponics",
      "greenhouseFarming",
      "dairyFarming",
      "poultryFarming",
      "fishFarming",
      "seeds",
      "fertilizers",
      "pesticides",
      "agriculturalEquipment",
      "organicCertified",
      "fssaiCertified",
      "qualityCheck",
      "deliveryAvailable",
      "wholesaleAvailable",
      "retailAvailable",
      "exportAvailable",
    ],
  },
  // Tours & Travels
  "tours-travels": {
    apiBase: "/api/admin/tours-travels",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "businessName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "city",
      "state",
      "fullAddress",
      "serviceAreas",
      "operatingCountries",
      "operatingStates",
      "startingPrice",
      "maxPrice",
      "domesticTours",
      "internationalTours",
      "adventureTours",
      "beachTours",
      "hillStationTours",
      "heritageTours",
      "wildlifeTours",
      "pilgrimageTours",
      "honeymoonTours",
      "familyTours",
      "corporateTours",
      "customPackages",
      "accommodationIncluded",
      "mealIncluded",
      "transportIncluded",
      "guideAvailable",
      "flightBooking",
      "hotelBooking",
      "carRental",
      "visaAssistance",
      "pickupAvailable",
      "dropAvailable",
      "experienceYears",
      "certifications",
      "languagesKnown",
      "workingHours",
      "available24_7",
      "images",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "domesticTours",
      "internationalTours",
      "adventureTours",
      "beachTours",
      "hillStationTours",
      "heritageTours",
      "wildlifeTours",
      "pilgrimageTours",
      "honeymoonTours",
      "familyTours",
      "corporateTours",
      "customPackages",
      "accommodationIncluded",
      "mealIncluded",
      "transportIncluded",
      "guideAvailable",
      "flightBooking",
      "hotelBooking",
      "carRental",
      "visaAssistance",
      "pickupAvailable",
      "dropAvailable",
    ],
  },
  // Hotels & Resorts
  "hotels-resorts": {
    apiBase: "/api/admin/hotels-resorts",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "propertyType",
      "businessName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "starRating",
      "city",
      "state",
      "fullAddress",
      "areaName",
      "numberOfRooms",
      "checkInTime",
      "checkOutTime",
      "pricePerNight",
      "wifiAvailable",
      "parkingAvailable",
      "restaurantAvailable",
      "barAvailable",
      "roomService",
      "laundryService",
      "gymAvailable",
      "poolAvailable",
      "spaAvailable",
      "conferenceRoom",
      "banquetHall",
      "airportTransfer",
      "petFriendly",
      "onlineBookingAvailable",
      "instantBooking",
      "freeCancellation",
      "payAtHotel",
      "couplesFriendly",
      "languagesKnown",
      "workingHours",
      "images",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "wifiAvailable",
      "parkingAvailable",
      "restaurantAvailable",
      "barAvailable",
      "roomService",
      "laundryService",
      "gymAvailable",
      "poolAvailable",
      "spaAvailable",
      "conferenceRoom",
      "banquetHall",
      "airportTransfer",
      "petFriendly",
      "onlineBookingAvailable",
      "instantBooking",
      "freeCancellation",
      "payAtHotel",
      "couplesFriendly",
    ],
  },
  // Event/Movie Ticket Booking
  "event-ticket-booking": {
    apiBase: "/api/admin/event-tickets",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "eventType",
      "businessName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "venueName",
      "venueAddress",
      "city",
      "state",
      "eventDate",
      "eventEndDate",
      "eventTime",
      "eventEndTime",
      "ticketPriceMin",
      "ticketPriceMax",
      "freeEntry",
      "vipSeating",
      "generalSeating",
      "onlineBooking",
      "offlineBooking",
      "payAtVenue",
      "instantConfirmation",
      "refundAvailable",
      "earlyBirdAvailable",
      "groupDiscount",
      "studentDiscount",
      "seniorDiscount",
      "childDiscount",
      "ageRestriction",
      "language",
      "duration",
      "organizerName",
      "artistPerformer",
      "featuredEvent",
      "popularEvent",
      "capacity",
      "workingHours",
      "images",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "freeEntry",
      "vipSeating",
      "generalSeating",
      "onlineBooking",
      "offlineBooking",
      "payAtVenue",
      "instantConfirmation",
      "refundAvailable",
      "earlyBirdAvailable",
      "groupDiscount",
      "studentDiscount",
      "seniorDiscount",
      "childDiscount",
      "featuredEvent",
      "popularEvent",
    ],
  },
  // Pet Care & Pet Food
  "pet-care-pet-food": {
    apiBase: "/api/admin/pet-care",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceCategory",
      "businessName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "city",
      "state",
      "fullAddress",
      "petGrooming",
      "petBoarding",
      "petDaycare",
      "petTraining",
      "petWalking",
      "petSitting",
      "veterinaryService",
      "petPhotography",
      "petInsurance",
      "homeVisit",
      "clinicVisit",
      "onlineConsultation",
      "emergencyService",
      "petFoodAvailable",
      "petToysAvailable",
      "petAccessoriesAvailable",
      "organicPetFood",
      "grainFreeFood",
      "prescriptionFood",
      "puppyFood",
      "adultDogFood",
      "seniorDogFood",
      "catFood",
      "fishFood",
      "birdFood",
      "deliveryAvailable",
      "freeDelivery",
      "licensedVet",
      "certifiedTrainer",
      "experienceYears",
      "certifications",
      "consultationFee",
      "groomingPrice",
      "boardingPricePerDay",
      "petFoodBrands",
      "workingHours",
      "languagesKnown",
      "images",
      "isActive",
      "isFeatured",
    ],
    featureKeys: [
      "petGrooming",
      "petBoarding",
      "petDaycare",
      "petTraining",
      "petWalking",
      "petSitting",
      "veterinaryService",
      "petPhotography",
      "petInsurance",
      "homeVisit",
      "clinicVisit",
      "onlineConsultation",
      "emergencyService",
      "petFoodAvailable",
      "petToysAvailable",
      "petAccessoriesAvailable",
      "organicPetFood",
      "grainFreeFood",
      "prescriptionFood",
      "deliveryAvailable",
      "freeDelivery",
      "licensedVet",
      "certifiedTrainer",
    ],
  },
  // Sales & Marketing Services
  "sales-marketing": {
    apiBase: "/api/admin/sales-marketing",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: ["serviceCategory", "businessName", "contactPerson", "contactPhone", "contactEmail", "website", "city", "state", "startingPrice", "hourlyRate", "teamSize", "experienceYears", "certifications", "digitalMarketing", "seoServices", "socialMediaMarketing", "leadGeneration", "isActive", "isFeatured"],
    featureKeys: ["digitalMarketing", "seoServices", "socialMediaMarketing", "contentMarketing", "emailMarketing", "ppcAdvertising", "brandMarketing", "leadGeneration", "freeConsultation", "freeDemo", "certifiedExperts", "guaranteedResults"],
  },
  // Courier & Cargo Services
  "courier-cargo": {
    apiBase: "/api/admin/courier-cargo",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: ["serviceCategory", "businessName", "contactPerson", "contactPhone", "contactEmail", "website", "city", "state", "perKgRate", "minimumCharge", "fleetSize", "experienceYears", "domesticDelivery", "internationalDelivery", "expressDelivery", "trackingAvailable", "insuranceAvailable", "isActive", "isFeatured"],
    featureKeys: ["domesticDelivery", "internationalDelivery", "expressDelivery", "standardDelivery", "overnightDelivery", "sameDayDelivery", "doorToDoor", "packingService", "fragileHandling", "trackingAvailable", "realTimeTracking", "insuranceAvailable", "codAvailable", "freePickup", "isoCertified"],
  },
  // News & Media
  "news-media": {
    apiBase: "/api/admin/news-media",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: ["channelType", "channelName", "language", "region", "contactPerson", "contactPhone", "contactEmail", "website", "city", "state", "subscribers", "viewership", "circulation", "printEdition", "digitalEdition", "televisionChannel", "youtubeChannel", "podcast", "isActive", "isFeatured"],
    featureKeys: ["printEdition", "digitalEdition", "onlineNews", "breakingNews", "dailyNews", "weeklyNews", "monthlyMagazine", "televisionChannel", "radioChannel", "youtubeChannel", "podcast", "newsPortal", "ePaperAvailable", "subscriptionAvailable", "liveStreaming"],
  },
  // Restaurants
  "restaurants": {
    apiBase: "/api/admin/restaurants",
    titleField: "title",
    subtitleField: "restaurantName",
    defaultFields: [
      "restaurantName",
      "cuisineType",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "city",
      "state",
      "fullAddress",
      "openingTime",
      "closingTime",
      "seatingCapacity",
      "averageCostPerPerson",
      "priceRange",
      "parkingAvailable",
      "wifiAvailable",
      "airConditioned",
      "homeDelivery",
      "takeawayAvailable",
      "dineInAvailable",
      "outdoorSeating",
      "rooftopAvailable",
      "liveMusic",
      "liveStreaming",
      "gamingArea",
      "kidsPlayArea",
      "petFriendly",
      "servingAlcohol",
      "barAvailable",
      "smokingArea",
      "buffetAvailable",
      "pureVeg",
      "veganOptions",
      "organicFood",
      "halaCertified",
      "kosherCertified",
      "creditCardAccepted",
      "upiPayments",
      "onlineBookingAvailable",
      "tableReservation",
      "instantBooking",
      "freeCancellation",
      "languagesKnown",
      "certifications",
      "amenities",
      "images",
      "isActive",
      "isFeatured",
      "viewCount",
    ],
    featureKeys: [
      "parkingAvailable",
      "wifiAvailable",
      "airConditioned",
      "homeDelivery",
      "takeawayAvailable",
      "dineInAvailable",
      "outdoorSeating",
      "rooftopAvailable",
      "liveMusic",
      "liveStreaming",
      "gamingArea",
      "kidsPlayArea",
      "petFriendly",
      "servingAlcohol",
      "barAvailable",
      "smokingArea",
      "buffetAvailable",
      "pureVeg",
      "veganOptions",
      "organicFood",
      "halaCertified",
      "kosherCertified",
      "creditCardAccepted",
      "upiPayments",
      "onlineBookingAvailable",
      "tableReservation",
      "instantBooking",
      "freeCancellation",
    ],
  },
  // Cafes
  "cafes": {
    apiBase: "/api/admin/cafes",
    titleField: "title",
    subtitleField: "cafeName",
    defaultFields: [
      "cafeName",
      "cafeType",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "city",
      "state",
      "fullAddress",
      "openingTime",
      "closingTime",
      "seatingCapacity",
      "averageCostPerPerson",
      "priceRange",
      "parkingAvailable",
      "wifiAvailable",
      "airConditioned",
      "homeDelivery",
      "takeawayAvailable",
      "dineInAvailable",
      "outdoorSeating",
      "rooftopAvailable",
      "liveMusic",
      "boardGames",
      "gamingArea",
      "meetingRooms",
      "studyArea",
      "petFriendly",
      "servingAlcohol",
      "shishaAvailable",
      "smokingArea",
      "bakeryAvailable",
      "dessertMenu",
      "specialtyCoffee",
      "teaMenu",
      "smoothieBowls",
      "pancakeWaffles",
      "pureVeg",
      "veganOptions",
      "organicFood",
      "creditCardAccepted",
      "upiPayments",
      "onlineOrdering",
      "instantBooking",
      "languagesKnown",
      "certifications",
      "amenities",
      "images",
      "isActive",
      "isFeatured",
      "viewCount",
    ],
    featureKeys: [
      "parkingAvailable",
      "wifiAvailable",
      "airConditioned",
      "homeDelivery",
      "takeawayAvailable",
      "dineInAvailable",
      "outdoorSeating",
      "rooftopAvailable",
      "liveMusic",
      "boardGames",
      "gamingArea",
      "meetingRooms",
      "studyArea",
      "petFriendly",
      "servingAlcohol",
      "shishaAvailable",
      "smokingArea",
      "bakeryAvailable",
      "dessertMenu",
      "specialtyCoffee",
      "teaMenu",
      "smoothieBowls",
      "pancakeWaffles",
      "pureVeg",
      "veganOptions",
      "organicFood",
      "creditCardAccepted",
      "upiPayments",
      "onlineOrdering",
      "instantBooking",
    ],
  },
  // Home Delivery Services
  "home-delivery": {
    apiBase: "/api/admin/home-delivery",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceType",
      "businessName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "city",
      "state",
      "fullAddress",
      "deliveryZones",
      "deliveryCoverageArea",
      "minimumOrderAmount",
      "deliveryCharges",
      "freeDeliveryAbove",
      "freeDelivery",
      "minimumDeliveryTime",
      "maximumDeliveryTime",
      "deliveryTimeUnit",
      "sameDayDelivery",
      "expressDelivery",
      "scheduledDelivery",
      "pickupAvailable",
      "contactlessDelivery",
      "temperatureControlledDelivery",
      "packagingAvailable",
      "ecoFriendlyPackaging",
      "frozenDelivery",
      "hotFoodDelivery",
      "cashOnDelivery",
      "onlinePayment",
      "upiPayments",
      "creditCardAccepted",
      "walletPayments",
      "installmentsAvailable",
      "returnPolicy",
      "exchangePolicy",
      "customerSupportAvailable",
      "orderTracking",
      "liveOrderTracking",
      "deliveryPersonTracking",
      "estimatedTimeDisplay",
      "deliveryExecutiveApp",
      "bulkOrders",
      "corporateOrders",
      "subscriptionOrders",
      "workingHours",
      "languagesKnown",
      "certifications",
      "amenities",
      "images",
      "isActive",
      "isFeatured",
      "viewCount",
    ],
    featureKeys: [
      "freeDelivery",
      "sameDayDelivery",
      "expressDelivery",
      "scheduledDelivery",
      "pickupAvailable",
      "contactlessDelivery",
      "temperatureControlledDelivery",
      "packagingAvailable",
      "ecoFriendlyPackaging",
      "frozenDelivery",
      "hotFoodDelivery",
      "cashOnDelivery",
      "onlinePayment",
      "upiPayments",
      "creditCardAccepted",
      "walletPayments",
      "installmentsAvailable",
      "customerSupportAvailable",
      "orderTracking",
      "liveOrderTracking",
      "bulkOrders",
      "corporateOrders",
      "subscriptionOrders",
    ],
  },
  // Catering Services
  "catering": {
    apiBase: "/api/admin/catering",
    titleField: "title",
    subtitleField: "businessName",
    defaultFields: [
      "serviceType",
      "businessName",
      "contactPerson",
      "contactPhone",
      "contactEmail",
      "whatsappAvailable",
      "website",
      "city",
      "state",
      "fullAddress",
      "minimumGuestCapacity",
      "maximumGuestCapacity",
      "pricePerPlate",
      "pricePerPlateMin",
      "pricePerPlateMax",
      "menuType",
      "cuisineSpecialization",
      "vegetarianAvailable",
      "nonVegetarianAvailable",
      "veganOptions",
      "jainFood",
      "dietSpecific",
      "halaCertified",
      "kosherCertified",
      "outdoorCatering",
      "destinationCatering",
      "corporateCatering",
      "weddingCatering",
      "partyCatering",
      "birthdayCatering",
      "themeMenu",
      "liveCooking",
      "liveCounter",
      "barService",
      "beverageService",
      "dessertService",
      "cakeCutting",
      "waitstaffService",
      "serversProvided",
      "chefsProvided",
      "cookingStaffProvided",
      "servingEquipment",
      "diningSetup",
      "tentHouse",
      "decorations",
      "themeDecorations",
      "flowersDecorations",
      "lightingDecorations",
      "seatingArrangement",
      "cleanupService",
      "wasteManagement",
      "menuCustomization",
      "tastingSession",
      "foodPresentation",
      "dietaryRequirements",
      "allergyConsideration",
      "specialMenuPlanning",
      "foodSafetyCertified",
      "licensesHeld",
      "insuranceCovered",
      "pickupDelivery",
      "homeDelivery",
      "setupService",
      "paymentOptions",
      "advanceBooking",
      "bookingPolicy",
      "cancellationPolicy",
      "workingHours",
      "languagesKnown",
      "certifications",
      "portfolio",
      "images",
      "isActive",
      "isFeatured",
      "viewCount",
    ],
    featureKeys: [
      "vegetarianAvailable",
      "nonVegetarianAvailable",
      "veganOptions",
      "jainFood",
      "dietSpecific",
      "halaCertified",
      "kosherCertified",
      "outdoorCatering",
      "destinationCatering",
      "corporateCatering",
      "weddingCatering",
      "partyCatering",
      "birthdayCatering",
      "themeMenu",
      "liveCooking",
      "liveCounter",
      "barService",
      "beverageService",
      "dessertService",
      "cakeCutting",
      "waitstaffService",
      "serversProvided",
      "chefsProvided",
      "cookingStaffProvided",
      "servingEquipment",
      "diningSetup",
      "tentHouse",
      "decorations",
      "themeDecorations",
      "flowersDecorations",
      "lightingDecorations",
      "seatingArrangement",
      "cleanupService",
      "menuCustomization",
      "tastingSession",
      "foodSafetyCertified",
      "insuranceCovered",
      "pickupDelivery",
      "homeDelivery",
      "setupService",
      "advanceBooking",
    ],
  },
};

export const getConfigForType = (type: string) => {
  return listingConfigs[type];
};
