// Shared mapping of subcategory slugs -> API endpoints and display names
export const SUBCATEGORY_API_MAP: Record<string, string> = {
  'TuitionPrivatClasses': '/api/tuition-private-classes',
  'Tuition & Private Classes': '/api/tuition-private-classes',
  'RentalListings': '/api/rental-listings',
  'Rental Listings': '/api/rental-listings',
  'HostelPG': '/api/hostel-listings',
  'Hostel & PG': '/api/hostel-listings',
  'ConstructionMaterials': '/api/construction-materials',
  'Construction Materials': '/api/construction-materials',
  'Construction & Building Materials': '/api/construction-materials',
  'PropertyDeals': '/api/property-deals-public',
  'Property Deals': '/api/property-deals-public',
  'CommercialProperties': '/api/commercial-properties-public',
  'Commercial Properties': '/api/commercial-properties-public',
  'IndustrialLand': '/api/industrial-land-public',
  'Industrial Land': '/api/industrial-land-public',
  'OfficeSpaces': '/api/office-spaces-public',
  'Office Spaces': '/api/office-spaces-public',
  'LocalMarketCommercialProperty': '/api/commercial-properties-public',
  'Local Market Commercial Property': '/api/commercial-properties-public',
  'OfficeSpacesPublic': '/api/office-spaces-public',
  'CompanyOfficeSpace': '/api/office-spaces-public',
  'Company Office Space': '/api/office-spaces-public',
  'IndustrialLandPublic': '/api/industrial-land-public',
  'FactoryIndustrialLand': '/api/industrial-land-public',
  'Factory Industrial Land': '/api/industrial-land-public',
  'Rentals': '/api/rental-listings',
  'Rental - Rooms, Flats, Apartments': '/api/rental-listings',
  'Rental - Rooms, Flats, Apartiments': '/api/rental-listings',
  'HostelPg': '/api/hostel-listings',
  'Hostels & PG': '/api/hostel-listings',
  'CarsBikes': '/api/cars-bikes',
  'Cars & Bikes': '/api/cars-bikes',
  'HeavyEquipment': '/api/heavy-equipment',
  'Heavy Equipment': '/api/heavy-equipment',
  'Heavy Equipment for Sale': '/api/heavy-equipment',
  'Heavy Equipment For Sale': '/api/heavy-equipment',
  'Showrooms': '/api/showrooms',
  'Showrooms (Authorized Second-Hand)': '/api/showrooms',
  'Showrooms (Authorized-Second-hand)': '/api/showrooms',
  'SecondHandCarsBikes': '/api/second-hand-cars-bikes-public',
  'Second Hand Cars & Bikes': '/api/second-hand-cars-bikes-public',
  'Second-Hand Cars & Bikes': '/api/second-hand-cars-bikes-public',
  'CarBikeRentals': '/api/car-bike-rental-public',
  'Car & Bike Rentals': '/api/car-bike-rental-public',
  'TransportationMovingServices': '/api/transportation-moving-services',
  'Transportation & Moving Services': '/api/transportation-moving-services',
  'VehicleLicenseClasses': '/api/vehicle-license-classes',
  'Vehicle License Classes': '/api/vehicle-license-classes',
  'ElectronicsGadgets': '/api/electronics-gadgets',
  'Electronics & Gadgets': '/api/electronics-gadgets',
  'PhonesTabletsAccessories': '/api/phones-tablets-accessories',
  'Phones, Tablets & Accessories': '/api/phones-tablets-accessories',
  'New Phones & Tablets & Accessories': '/api/phones-tablets-accessories',
  'New Phones & Tablets & Accessories ': '/api/phones-tablets-accessories',
  'SecondHandPhonesTabletsAccessories': '/api/second-hand-phones-tablets-accessories',
  'Second Hand Phones & Accessories': '/api/second-hand-phones-tablets-accessories',
  'Second Hand Phones & Tablets & Accessories': '/api/second-hand-phones-tablets-accessories',
  'Second-Hand Phones & Tablets & Accessories': '/api/second-hand-phones-tablets-accessories',
  'ComputerMobileLaptopRepairServices': '/api/computer-mobile-laptop-repair-services',
  'Computer & Mobile Repair Services': '/api/computer-mobile-laptop-repair-services',
  'Computer, Mobile & Laptop Repair Services': '/api/computer-mobile-laptop-repair-services',
  'CyberCafeInternetServices': '/api/cyber-cafe-internet-services',
  'Cyber Cafe & Internet Services': '/api/cyber-cafe-internet-services',
  'Cyber café & Internet Services': '/api/cyber-cafe-internet-services',
  'Cyber Café / Internet Services': '/api/cyber-cafe-internet-services',
  'TelecommunicationServices': '/api/telecommunication-services',
  'Telecommunication Services': '/api/telecommunication-services',
  'ServiceCentreWarranty': '/api/service-centre-warranty',
  'Service Centre / Warranty': '/api/service-centre-warranty',
  'Service Centre & Warranty': '/api/service-centre-warranty',
  'Service Centre % Warranty': '/api/service-centre-warranty',
  'FurnitureInteriorDecor': '/api/furniture-decor',
  'Furniture & Interior Decor': '/api/furniture-decor',
  'furniture': '/api/furniture-decor',
  'HouseholdServices': '/api/household-services',
  'Household Services': '/api/household-services',
  'EventDecorationServices': '/api/event-decoration-services',
  'Event & Decoration Services': '/api/event-decoration-services',
  'Event & Decoration Services (Marriage Halls, Parties, Café Setup, Decoration Materials)': '/api/event-decoration-services',
  'FashionBeautyProducts': '/api/fashion-beauty',
  'Fashion & Beauty Products': '/api/fashion-beauty',
  'SareeClothingShopping': '/api/saree-clothing',
  'Saree & Clothing Shopping': '/api/saree-clothing',
  'Saree Shopping Clothing': '/api/saree-clothing',
  'EbooksOnlineCourses': '/api/ebooks-online-courses',
  'E-Books & Online Courses': '/api/ebooks-online-courses',
  'CricketSportsTraining': '/api/cricket-sports-training',
  'Cricket & Sports Training': '/api/cricket-sports-training',
  'PharmacyMedicalStores': '/api/pharmacy-medical',
  'Pharmacy & Medical Stores': '/api/pharmacy-medical',
  'DanceKarateGymYoga': '/api/dance-karate-gym-yoga',
  'Dance, Karate, Gym & Yoga': '/api/dance-karate-gym-yoga',
  'DanceKarateGymYoga Classes': '/api/dance-karate-gym-yoga',
  'LanguageClasses': '/api/language-classes',
  'Language Classes': '/api/language-classes',
  'AcademiesMusicArtsSports': '/api/academy-music-arts',
  'Academies - Music, Arts, Sports': '/api/academy-music-arts',
  'Academies-Music-Arts-Sports': '/api/academy-music-arts',
  'SkillTrainingCertification': '/api/skill-training-certification',
  'Skill Training & Certification': '/api/skill-training-certification',
  'Skill-Training -Certification': '/api/skill-training-certification',
  'SchoolsCollegesCoaching': '/api/schools-colleges-coaching',
  'Schools, Colleges & Coaching': '/api/schools-colleges-coaching',
  'Schools, Colleges, Coaching Institutes': '/api/schools-colleges-coaching',
  'Cricket-Sports Training': '/api/cricket-sports-training',
  'EducationalConsultancyStudyAbroad': '/api/educational-consultancy-study-abroad',
  'Educational Consultancy & Study Abroad': '/api/educational-consultancy-study-abroad',
  'educational-consultancy-study-abroad': '/api/educational-consultancy-study-abroad',
  'JewelryAccessories': '/api/jewelry-accessories',
  'Jewelry & Accessories': '/api/jewelry-accessories',
  'HealthWellnessServices': '/api/health-wellness',
  'Health & Wellness Services': '/api/health-wellness',
  'AgentsAgencies': '/api/admin/agents-agencies',
  'Agents & Agencies': '/api/admin/agents-agencies',
  'ProfessionalProfileExpertiseListing': '/api/admin/professional-services',
  'Professional Profile & Expertise Listing': '/api/admin/professional-services',
  'LaborWorkerServices': '/api/admin/labor-worker-services',
  'Labor & Worker Services': '/api/admin/labor-worker-services',
  'EngineeringITServices': '/api/admin/engineering-it-services',
  'Engineering & IT Services': '/api/admin/engineering-it-services',
  'LegalBankingServices': '/api/admin/legal-banking-services',
  'Legal & Banking Services': '/api/admin/legal-banking-services',
  'LegalBankingLoanLandSurveyingServices': '/api/admin/legal-banking-services',
  'Legal, Banking, Loan & Land Surveying Services': '/api/admin/legal-banking-services',
  'InsuranceServices': '/api/admin/insurance-services',
  'Insurance Services': '/api/admin/insurance-services',
  'NGOsSocialServices': '/api/admin/ngo-social-services',
  'NGOs & Social Services': '/api/admin/ngo-social-services',
  'ToursTravels': '/api/admin/tours-travels',
  'Tours & Travels': '/api/admin/tours-travels',
  'HotelsResorts': '/api/admin/hotels-resorts',
  'Hotels & Resorts': '/api/admin/hotels-resorts',
  'EventTicketBooking': '/api/admin/event-tickets',
  'Event/MovieTicketBooking': '/api/admin/event-tickets',
  'Event & Movie Ticket Booking': '/api/admin/event-tickets',
  'PetCarePetFood': '/api/admin/pet-care',
  'PetCare&PetFood': '/api/admin/pet-care',
  'Pet Care & Pet Food': '/api/admin/pet-care',
  'AgricultureSeedsFarming': '/api/admin/agriculture',
  'Agriculture,Seeds&Farming': '/api/admin/agriculture',
  'Agriculture, Seeds & Farming': '/api/admin/agriculture',
  'SalesMarketing': '/api/admin/sales-marketing',
  'Sales & Marketing': '/api/admin/sales-marketing',
  'Sales%20%26%20Marketing': '/api/admin/sales-marketing',
  'SalesMarketingServices': '/api/admin/sales-marketing',
  'Sales & Marketing Services': '/api/admin/sales-marketing',
  'Sales%20%26%20Marketing%20Services': '/api/admin/sales-marketing',
  'NewsMedia': '/api/admin/news-media',
  'News & Media': '/api/admin/news-media',
  'News & Media Services': '/api/admin/news-media',
  'CourierCargoServices': '/api/admin/courier-cargo',
  'Courier & Cargo Services': '/api/admin/courier-cargo',
  'Courier%20%26%20Cargo%20Services': '/api/admin/courier-cargo',
  'Restaurants': '/api/restaurants',
  'Restaurant': '/api/restaurants',
  'Cafes': '/api/cafes',
  'Cafe': '/api/cafes',
  'HomeDelivery': '/api/home-delivery',
  'Home Delivery': '/api/home-delivery',
  'Catering': '/api/catering',
  'CateringServices': '/api/catering',
  'Catering Services': '/api/catering',
  'ClinicsHospitals': '/api/clinics-hospitals',
  'Clinics & Hospitals': '/api/clinics-hospitals',
  'DiagnosticLabs': '/api/diagnostic-labs',
  'Diagnostic Labs': '/api/diagnostic-labs',
  'FitnessTrainers': '/api/fitness-trainers',
  'Fitness Trainers': '/api/fitness-trainers',
  'GymsFitnessCenters': '/api/gyms-fitness-centers',
  'Gyms & Fitness Centers': '/api/gyms-fitness-centers',
  'SportsEquipment': '/api/sports-equipment',
  'Sports Equipment': '/api/sports-equipment',
  'MusicEntertainment': '/api/music-entertainment',
  'Music & Entertainment': '/api/music-entertainment',
  'Music%20%26%20Entertainment%20Services': '/api/music-entertainment',
  'MusicEntertainmentServices': '/api/music-entertainment',
  'Music & Entertainment Services': '/api/music-entertainment',
  'GroceryDailyEssentials': '/api/grocery-daily-essentials',
  'Grocery & Daily Essentials': '/api/grocery-daily-essentials',
  'Grocery%20%26%20Daily%20Essentials': '/api/grocery-daily-essentials',
  'CleaningPestControl': '/api/cleaning-pest-control',
  'Cleaning & Pest Control': '/api/cleaning-pest-control',
  'Cleaning%20%26%20Pest%20Control': '/api/cleaning-pest-control',
  'ElectricalPlumbingRepairs': '/api/electrical-plumbing-repairs',
  'Electrical/Plumbing Repairs': '/api/electrical-plumbing-repairs',
  'Electrical/Plumbing%20Repairs': '/api/electrical-plumbing-repairs',
  'AccountingAudit': '/api/accounting-audit',
  'Accounting & Audit': '/api/accounting-audit',
  'Accounting%20%26%20Audit': '/api/accounting-audit',
  'InvestmentOpportunities': '/api/investment-opportunities',
  'Investment Opportunities': '/api/investment-opportunities',
  'Investment%20Opportunities': '/api/investment-opportunities',
  'MicrofinanceCooperative': '/api/microfinance-cooperative',
  'Microfinance/Cooperative Listings': '/api/microfinance-cooperative',
  'Microfinance/Cooperative%20Listings': '/api/microfinance-cooperative',
};

export const SUBCATEGORY_NAMES: Record<string, string> = {
  'TuitionPrivatClasses': 'Tuition & Private Classes',
  'RentalListings': 'Rental Listings',
  'HostelPG': 'Hostel & PG',
  'ConstructionMaterials': 'Construction Materials',
  'Construction & Building Materials': 'Construction & Building Materials',
  'PropertyDeals': 'Property Deals',
  'CommercialProperties': 'Commercial Properties',
  'IndustrialLand': 'Industrial Land',
  'OfficeSpaces': 'Office Spaces',
  'CarsBikes': 'Cars & Bikes',
  'HeavyEquipment': 'Heavy Equipment',
  'Showrooms': 'Showrooms',
  'SecondHandCarsBikes': 'Second Hand Cars & Bikes',
  'CarBikeRentals': 'Car & Bike Rentals',
  'TransportationMovingServices': 'Transportation & Moving Services',
  'VehicleLicenseClasses': 'Vehicle License Classes',
  'ElectronicsGadgets': 'Electronics & Gadgets',
  'PhonesTabletsAccessories': 'Phones, Tablets & Accessories',
  'New Phones & Tablets & Accessories': 'New Phones, Tablets & Accessories',
  'SecondHandPhonesTabletsAccessories': 'Second Hand Phones & Accessories',
  'ComputerMobileLaptopRepairServices': 'Computer & Mobile Repair Services',
  'CyberCafeInternetServices': 'Cyber Café / Internet Services',
  'FurnitureInteriorDecor': 'Furniture & Interior Decor',
  'HouseholdServices': 'Household Services',
  'EventDecorationServices': 'Event & Decoration Services',
  'FashionBeautyProducts': 'Fashion & Beauty Products',
  'SareeClothingShopping': 'Saree & Clothing Shopping',
  'EbooksOnlineCourses': 'E-Books & Online Courses',
  'CricketSportsTraining': 'Cricket & Sports Training',
  'PharmacyMedicalStores': 'Pharmacy & Medical Stores',
  'DanceKarateGymYoga': 'Dance, Karate, Gym & Yoga',
  'DanceKarateGymYoga Classes': 'Dance, Karate, Gym & Yoga',
  'LanguageClasses': 'Language Classes',
  'AcademiesMusicArtsSports': 'Academies - Music, Arts, Sports',
  'SkillTrainingCertification': 'Skill Training & Certification',
  'SchoolsCollegesCoaching': 'Schools, Colleges & Coaching',
  'EducationalConsultancyStudyAbroad': 'Educational Consultancy & Study Abroad',
  'JewelryAccessories': 'Jewelry & Accessories',
  'HealthWellnessServices': 'Health & Wellness Services',
  'TelecommunicationServices': 'Telecommunication Services',
  'ServiceCentreWarranty': 'Service Centre & Warranty',
  'ToursTravels': 'Tours & Travels',
  'HotelsResorts': 'Hotels & Resorts',
  'Event/MovieTicketBooking': 'Event & Movie Ticket Booking',
  'EventTicketBooking': 'Event & Movie Ticket Booking',
  'PetCare&PetFood': 'Pet Care & Pet Food',
  'PetCarePetFood': 'Pet Care & Pet Food',
  'AgricultureSeedsFarming': 'Agriculture, Seeds & Farming',
  'Agriculture,Seeds&Farming': 'Agriculture, Seeds & Farming',
  'SalesMarketing': 'Sales & Marketing',
  'Sales&Marketing': 'Sales & Marketing',
  'SalesMarketingServices': 'Sales & Marketing Services',
  'Sales & Marketing Services': 'Sales & Marketing Services',
  'CourierCargo': 'Courier & Cargo',
  'Courier&Cargo': 'Courier & Cargo',
  'CourierCargoServices': 'Courier & Cargo Services',
  'Courier & Cargo Services': 'Courier & Cargo Services',
  'NewsMedia': 'News & Media',
  'News&Media': 'News & Media',
  'Courier%20%26%20Cargo': 'Courier & Cargo',
  'Sales%20%26%20Marketing': 'Sales & Marketing',
  'Sales%20%26%20Marketing%20Services': 'Sales & Marketing Services',
  'Courier%20%26%20Cargo%20Services': 'Courier & Cargo Services',
  'News%20%26%20Media': 'News & Media',
  'Restaurants': 'Restaurants',
  'Restaurant': 'Restaurants',
  'Cafes': 'Cafes',
  'Cafe': 'Cafes',
  'HomeDelivery': 'Home Delivery Services',
  'Home Delivery': 'Home Delivery Services',
  'Catering': 'Catering Services',
  'CateringServices': 'Catering Services',
  'Catering Services': 'Catering Services',
  'ClinicsHospitals': 'Clinics & Hospitals',
  'Clinics & Hospitals': 'Clinics & Hospitals',
  'DiagnosticLabs': 'Diagnostic Labs',
  'Diagnostic Labs': 'Diagnostic Labs',
  'FitnessTrainers': 'Fitness Trainers',
  'Fitness Trainers': 'Fitness Trainers',
  'GymsFitnessCenters': 'Gyms & Fitness Centers',
  'Gyms & Fitness Centers': 'Gyms & Fitness Centers',
  'SportsEquipment': 'Sports Equipment',
  'Sports Equipment': 'Sports Equipment',
  'MusicEntertainment': 'Music & Entertainment Services',
  'Music & Entertainment': 'Music & Entertainment Services',
  'Music%20%26%20Entertainment%20Services': 'Music & Entertainment Services',
  'MusicEntertainmentServices': 'Music & Entertainment Services',
  'Music & Entertainment Services': 'Music & Entertainment Services',
  'GroceryDailyEssentials': 'Grocery & Daily Essentials',
  'Grocery & Daily Essentials': 'Grocery & Daily Essentials',
  'CleaningPestControl': 'Cleaning & Pest Control',
  'Cleaning & Pest Control': 'Cleaning & Pest Control',
  'ElectricalPlumbingRepairs': 'Electrical/Plumbing Repairs',
  'Electrical/Plumbing Repairs': 'Electrical/Plumbing Repairs',
  'AccountingAudit': 'Accounting & Audit',
  'Accounting & Audit': 'Accounting & Audit',
  'InvestmentOpportunities': 'Investment Opportunities',
  'Investment Opportunities': 'Investment Opportunities',
  'MicrofinanceCooperative': 'Microfinance/Cooperative Listings',
  'Microfinance/Cooperative Listings': 'Microfinance/Cooperative Listings',
};

export default SUBCATEGORY_API_MAP;
