-- Professional Services Table
CREATE TABLE IF NOT EXISTS professional_services (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    service_category TEXT NOT NULL,
    business_name TEXT NOT NULL,
    professional_name TEXT NOT NULL,
    qualification TEXT,
    experience_years INTEGER,
    certifications TEXT,
    specialization TEXT,
    service_areas TEXT,
    hourly_rate DECIMAL(10,2),
    consultation_fee DECIMAL(10,2),
    free_consultation BOOLEAN DEFAULT false,
    home_service BOOLEAN DEFAULT false,
    online_service BOOLEAN DEFAULT false,
    emergency_service BOOLEAN DEFAULT false,
    licensed_professional BOOLEAN DEFAULT false,
    insured BOOLEAN DEFAULT false,
    verified BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    languages_known TEXT,
    website TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Labor & Worker Services Table
CREATE TABLE IF NOT EXISTS labor_worker_services (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    worker_type TEXT NOT NULL,
    business_name TEXT,
    worker_name TEXT NOT NULL,
    skills TEXT,
    experience TEXT,
    age INTEGER,
    gender TEXT,
    availability TEXT,
    hourly_rate DECIMAL(10,2),
    daily_rate DECIMAL(10,2),
    monthly_rate DECIMAL(10,2),
    free_demo BOOLEAN DEFAULT false,
    pickup_available BOOLEAN DEFAULT false,
    onsite_available BOOLEAN DEFAULT false,
    certified BOOLEAN DEFAULT false,
    background_verified BOOLEAN DEFAULT false,
    tools_provided BOOLEAN DEFAULT false,
    transport_available BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    language_known TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Engineering & IT Services Table
CREATE TABLE IF NOT EXISTS engineering_it_services (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    service_category TEXT NOT NULL,
    business_name TEXT NOT NULL,
    team_size INTEGER,
    founded_year INTEGER,
    specialization TEXT,
    technologies TEXT,
    certifications TEXT,
    service_areas TEXT,
    hourly_rate DECIMAL(10,2),
    project_based_pricing BOOLEAN DEFAULT false,
    free_consultation BOOLEAN DEFAULT false,
    remote_service BOOLEAN DEFAULT false,
    onsite_service BOOLEAN DEFAULT false,
    emergency_support BOOLEAN DEFAULT false,
    iso_certified BOOLEAN DEFAULT false,
    msme_registered BOOLEAN DEFAULT false,
    government_contractor BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    website TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    languages_known TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Legal, Banking, Loan & Land Surveying Services Table
CREATE TABLE IF NOT EXISTS legal_banking_services (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    service_category TEXT NOT NULL,
    business_name TEXT NOT NULL,
    firm_name TEXT,
    established_year INTEGER,
    specialization TEXT,
    license_number TEXT,
    bar_council_number TEXT,
    service_areas TEXT,
    consultation_fee DECIMAL(10,2),
    free_consultation BOOLEAN DEFAULT false,
    online_consultation BOOLEAN DEFAULT false,
    home_visit BOOLEAN DEFAULT false,
    court_representation BOOLEAN DEFAULT false,
    document_drafting BOOLEAN DEFAULT false,
    notarized BOOLEAN DEFAULT false,
    registered BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    website TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    languages_known TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Insurance Services Table
CREATE TABLE IF NOT EXISTS insurance_services (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    insurance_type TEXT NOT NULL,
    company_name TEXT NOT NULL,
    agent_name TEXT,
    license_number INTEGER,
    experience TEXT,
    specialization TEXT,
    covers TEXT,
    free_quote BOOLEAN DEFAULT false,
    online_purchase BOOLEAN DEFAULT false,
    home_visit BOOLEAN DEFAULT false,
    claim_assistance BOOLEAN DEFAULT false,
    cashless_claim BOOLEAN DEFAULT false,
    road_side_assistance BOOLEAN DEFAULT false,
    support_24x7 BOOLEAN DEFAULT false,
    tie_up_hospitals BOOLEAN DEFAULT false,
    network_garages BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- NGO & Social Services Table
CREATE TABLE IF NOT EXISTS ngo_social_services (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    ngo_type TEXT NOT NULL,
    organization_name TEXT NOT NULL,
    registration_number TEXT,
    founded_year INTEGER,
    mission TEXT,
    vision TEXT,
    focus_areas TEXT,
    target_beneficiaries TEXT,
    services_offered TEXT,
    volunteer_opportunities BOOLEAN DEFAULT false,
    donation_accepted BOOLEAN DEFAULT false,
    ngo_accredited BOOLEAN DEFAULT false,
    government_recognized BOOLEAN DEFAULT false,
    online_services BOOLEAN DEFAULT false,
    free_services BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    website TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    languages_known TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Agents & Agencies Table
CREATE TABLE IF NOT EXISTS agents_agencies (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    agency_type TEXT NOT NULL,
    agency_name TEXT NOT NULL,
    owner_name TEXT,
    established_year INTEGER,
    license_number TEXT,
    specialization TEXT,
    services TEXT,
    service_areas TEXT,
    team_size INTEGER,
    properties_handled INTEGER,
    verified BOOLEAN DEFAULT false,
    licensed BOOLEAN DEFAULT false,
    free_consultation BOOLEAN DEFAULT false,
    home_visit BOOLEAN DEFAULT false,
    online_service BOOLEAN DEFAULT false,
    emergency_service BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    website TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    languages_known TEXT,
    social_media_links TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);