-- Accounting & Audit Services Table
CREATE TABLE IF NOT EXISTS accounting_audit_services (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    service_category TEXT NOT NULL,
    business_name TEXT NOT NULL,
    firm_name TEXT,
    established_year INTEGER,
    qualification TEXT,
    specialization TEXT,
    certifications TEXT,
    service_areas TEXT,
    consultation_fee DECIMAL(10,2),
    audit_fee DECIMAL(10,2),
    free_consultation BOOLEAN DEFAULT false,
    tax_filing BOOLEAN DEFAULT false,
    gst_filing BOOLEAN DEFAULT false,
    payroll BOOLEAN DEFAULT false,
    financial_audit BOOLEAN DEFAULT false,
    bookkeeping BOOLEAN DEFAULT false,
    company_registration BOOLEAN DEFAULT false,
    certified BOOLEAN DEFAULT false,
    licensed BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    website TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    languages_known TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Investment Opportunities Table
CREATE TABLE IF NOT EXISTS investment_opportunities (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    investment_type TEXT NOT NULL,
    company_name TEXT NOT NULL,
    sector TEXT,
    business_plan TEXT,
    target_amount DECIMAL(15,2),
    min_investment DECIMAL(15,2),
    max_investment DECIMAL(15,2),
    expected_return TEXT,
    roi TEXT,
    investment_period TEXT,
    risk_level TEXT,
    location TEXT,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    verified BOOLEAN DEFAULT false,
    government_approved BOOLEAN DEFAULT false,
    sebi_registered BOOLEAN DEFAULT false,
    equity_offered BOOLEAN DEFAULT false,
    debt_offered BOOLEAN DEFAULT false,
    convertible_notes BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    website TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Microfinance & Cooperative Table
CREATE TABLE IF NOT EXISTS microfinance_cooperative (
    id VARCHAR(255) PRIMARY KEY DEFAULT (gen_random_uuid()::text),
    title TEXT NOT NULL,
    description TEXT,
    organization_type TEXT NOT NULL,
    organization_name TEXT NOT NULL,
    registration_number TEXT,
    established_year INTEGER,
    head_office TEXT,
    branches INTEGER,
    members INTEGER,
    sector TEXT,
    services TEXT,
    target_audience TEXT,
    min_loan_amount DECIMAL(15,2),
    max_loan_amount DECIMAL(15,2),
    interest_rate TEXT,
    processing_fee TEXT,
    collateral_required BOOLEAN DEFAULT false,
    government_registered BOOLEAN DEFAULT false,
    rbi_approved BOOLEAN DEFAULT false,
    sebi_registered BOOLEAN DEFAULT false,
    nbfc_certified BOOLEAN DEFAULT false,
    shg_finance BOOLEAN DEFAULT false,
    women_empowerment BOOLEAN DEFAULT false,
    farmer_finance BOOLEAN DEFAULT false,
    startup_funding BOOLEAN DEFAULT false,
    contact_person TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    contact_email TEXT,
    website TEXT,
    whatsapp_available BOOLEAN DEFAULT false,
    city TEXT,
    full_address TEXT NOT NULL,
    working_hours TEXT,
    available24_7 BOOLEAN DEFAULT false,
    languages_known TEXT,
    images JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    seller_id VARCHAR(255),
    seller_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);